exports.functionDef = {
  'hexString':{lib:'chroma',method:'hex',param:'rgb',result:'string'},
  'hex8String':{lib:'chroma',method:'hex',param:'rgba',result:'string'},
  'rgbString':{lib:'chroma',method:'css',param:'rgb',result:'string'},
  'rgbaString':{lib:'chroma',method:'css',param:'rgba',result:'string'},
  'hslString':{lib:'chroma',method:'css',param:'hsl',result:'string'},
  'hslaString':{lib:'chroma',method:'css',param:'hsla',result:'string'},
  'rgb':{lib:'chroma',method:'rgb',result:'array',params:['r','g','b']},
  'rgba':{lib:'chroma',method:'rgb',result:'array',params:['r','g','b','a']},
  'hsl':{lib:'chroma',method:'hsl',result:'array',params:['h','s','l']},
  'hsla':{lib:'chroma',method:'hsl',result:'array',params:['h','s','l','a']},
  'hsv':{lib:'chroma',method:'hsv',result:'array',params:['h','s','v']},
  'hsva':{lib:'chroma',method:'hsv',result:'array',params:['h','s','v','a']},
  'hsi':{lib:'chroma',method:'hsi',result:'array',params:['h','s','i']},
  'hsia':{lib:'chroma',method:'hsi',result:'array',params:['h','s','i','a']},
  'temperature':{lib:'chroma',method:'temperature',result:'number'},
  'name':{lib:'chroma',method:'name',result:'string'},
  'lab':{lib:'chroma',method:'lab',result:'array',params:['l','a','b']},
  'lch':{lib:'chroma',method:'lch',result:'array',params:['l','c','h']},
  'luminance':{lib:'chroma',method:'luminance',result:'number'},
  'rgbw':{lib:'chromaPlus',method:'rgbw',result:'object',params:['r','g','b','w']},
  'CIExyz':{lib:'chromaPlus',method:'xyz',result:'object',params:['x','y','z']},
  'CIExy':{lib:'chromaPlus',method:'xy',result:'object',params:['x','y']},
}
exports.percentProperties = ['s','v','l','i'];
